//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCount
    {
        public int Ma_NV { get; set; }
        public string TenTaiKhoan { get; set; }
        public string PassWord { get; set; }
        public string Quyen { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
