//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int Ma_DoanhThu { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<int> TongThu { get; set; }
    }
}
